version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    container_name: toposervis_web
    stdin_open: true
    tty: true
    volumes:
      - /opt/app/node_modules
      - .:/opt/app
    ports:
      - 3003:3003
    depends_on:
      - mysql
    entrypoint: /opt/app/run.dev

  mysql:
    image: mysql:5.5
    container_name: toposervis_mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=toposervis_dev
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/configs/my.cnf:/root/.my.cnf:ro