version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: toposervis_app
    stdin_open: true
    tty: true
    volumes:
      - /opt/app/node_modules
      - /opt/app/tmp
      - .:/opt/app
    ports:
      - 3003:3003
    depends_on:
      - db
    entrypoint: /opt/app/docker-entrypoint.sh

  db:
    image: mysql:5.5
    container_name: toposervis_db
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=toposervis_dev
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./.docker/configs/my.cnf:/root/.my.cnf:ro