#!/bin/bash
set -ex

CARPETA_PROYECTO="/var/www/localhost/htdocs/code"

# Cambiar el propietario de las carpetas para funcionar correctamente.
chown -R apache:apache $CARPETA_PROYECTO/public
chown -R apache:apache $CARPETA_PROYECTO/storage
chown -R apache:apache $CARPETA_PROYECTO/bootstrap

# Crear el archivo . env si no existe y generar la key de laravel.
AUX="$CARPETA_PROYECTO/.env"

if [ ! -f "$AUX" ]; then
  cp $CARPETA_PROYECTO/.env.example $AUX

  php $CARPETA_PROYECTO/artisan key:generate
fi

# Verificar si la carpeta symbolic link to -laravel existe para ejecutar nuestra aplicación.
AUX="/var/www/localhost/htdocs/laravel"

if [ ! -d "$AUX" ]; then
  ln -s $CARPETA_PROYECTO/public $AUX
fi

# Ejecutar Composer para instalar librerias solo si no existe la carpeta "vendor".
AUX="$CARPETA_PROYECTO/vendor"

if [ ! -d "$AUX" ]; then
  /usr/bin/compose install -d $CARPETA_PROYECTO
fi

echo "Clearing any old processes..."
rm -fr /run/apache2/httpd.pid

echo "Starting apache..."
/usr/sbin/httpd -D FOREGROUND