ProductLine.create(name:"GPS", description: "")
ProductLine.create(name:"ESTACIÓN TOTAL", description: "")
ProductLine.create(name:"EQUIPO DE COMPUTO", description: "")
ProductLine.create(name:"MATERIAL ELECTRICO", description: "")
ProductLine.create(name:"SOFTWARE", description: "")
ProductLine.create(name:"BATERIAS", description: "")
ProductLine.create(name:"dssadasd", description: "")
ProductLine.create(name:"NIVELO AUTOMATICO", description: "")
ProductLine.create(name:"ESTADAL", description: "")
ProductLine.create(name:"ACCESORIOS", description: "")
ProductLine.create(name:"ProMark 120 receptores con GPS L1/ Glonass ó ProMark 220 L1/L2 Glonass o RTK", description: "")
ProductLine.create(name:"NIVELES DIGITALES", description: "")
ProductLine.create(name:"SERVICIOS", description: "")