# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Role.create(name:"admin", description: "Administrador")
Role.create(name:"customer", description: "Cliente")
User.create(email: "admin@admin.com", name: "admin", lastname: "admin", password: "12345678", phone: "1234567890", role_id: 1)
User.create(email: "customer@customer.com", name: "customer", lastname: "customer", password: "12345678", phone: "1234567890", role_id: 2)
Accessory.create(name:"Accesorio Uno", description: "Esto es una descripción")
Currency.create(name:"MXN", description: "México", abbreviation: "MX", exchange_rate: 1.0)
Currency.create(name:"USD", description: "EEUU", abbreviation: "USD", exchange_rate: 25.0)
Unit.create(name:"Pieza", description: "Esto es una descripción", abbreviation: "PZ")
ProductLine.create(name:"Línea Uno", description: "Esto es una descripción")
Provider.create(name:"Proveedor Uno", rfc:"XAXX010101000", business_name: "Proveedor S.A de C.V")
ProviderAddress.create(street:"32", number:"100", crossing:"32 y 34", colony:"Fracc. Américas", town:"Mérida", state:"Yucatán", country:"México", provider_id: 1)
ProviderBank.create(beneficiary: "Dexter", account: "1234", clabe: "1234", bank_name: "BBVA", currency:"MXN", provider_id: 1)
ProviderContact.create(name: "Dexter", department:"Sistemas", phone:"9999999999", extension: "8", cellphone: "9999999999", email:"email@email.com", provider_id: 1)
Customer.create(name:"Cliente Uno", rfc:"XAXX010101000", business_name: "Proveedor S.A de C.V")
CustomerAddress.create(street:"32", number:"100", crossing:"32 y 34", colony:"Fracc. Américas", town:"Mérida", state:"Yucatán", country:"México", customer_id: 1)
CustomerBank.create(beneficiary: "Dexter", account: "1234", clabe: "1234", bank_name: "BBVA", currency:"MXN", customer_id: 1)
CustomerContact.create(name: "Dexter", department:"Sistemas", phone:"9999999999", extension: "8", cellphone: "9999999999", email:"email@email.com", customer_id: 1)
CategoryType.create(name:"Administrativos", description: "Administrativos")
CategoryType.create(name:"De operación", description: "De operación")
Category.create(name:"Telefonia", description: "Telefonia", category_type_id: 1)
Category.create(name:"Papeleria", description: "Papeleri", category_type_id: 1)
Category.create(name:"Nomina Oficina", description: "Nomina Oficina", category_type_id: 1)
Category.create(name:"Impuestos", description: "Impuestos", category_type_id: 1)
Category.create(name:"Honorarios", description: "Honorarios", category_type_id: 1)
Category.create(name:"Mensajeria", description: "Mensajeria", category_type_id: 1)
Category.create(name:"Tecnología", description: "Tecnología", category_type_id: 1)
Category.create(name:"Servicios", description: "Esto es una descripción", category_type_id: 1)
Category.create(name:"Mantenimiento y reparación de equipos", description: "Mantenimiento y reparación de equipos", category_type_id: 1)
Category.create(name:"Comisión", description: "Comisión", category_type_id: 1)
Category.create(name:"Interes", description: "Interes", category_type_id: 1)
Category.create(name:"Combustible", description: "Combustible", category_type_id: 1)
Category.create(name:"Mercancia", description: "Mercancia", category_type_id: 1)
Category.create(name:"Herramientas", description: "Herramientas", category_type_id: 1)
Category.create(name:"Despensas", description: "Despensas", category_type_id: 1)
Category.create(name:"Nomina Oficina", description: "Nomina Oficina", category_type_id: 1)
Category.create(name:"IMSS", description: "IMSS", category_type_id: 1)
Category.create(name:"Infonavit", description: "Infonavit", category_type_id: 1)
Category.create(name:"Otros", description: "Otros", category_type_id: 1)
Category.create(name:"Equipo de seguridad", description: "Mantenimiento y reparación de equipos", category_type_id: 2)
Category.create(name:"Combustible", description: "Comisión", category_type_id: 2)
Category.create(name:"Mantenimiento de vehiculos", description: "Interes", category_type_id: 2)
Category.create(name:"Herramientas", description: "Combustible", category_type_id: 2)
Category.create(name:"Materiales", description: "Mercancia", category_type_id: 2)
Category.create(name:"Insumos", description: "Herramientas", category_type_id: 2)
Category.create(name:"Nomina topografica", description: "Despensas", category_type_id: 2)
Category.create(name:"Viaticos", description: "Nomina Oficina", category_type_id: 2)
Category.create(name:"IMSS", description: "IMSS", category_type_id: 2)
Category.create(name:"Infonavit", description: "Infonavit", category_type_id: 2)
Category.create(name:"Otros", description: "Otros", category_type_id: 2)
Subcategory.create(name:"Subcategoria Uno", description: "Esto es una descripción", category_id: 1)
Condition.create(name:"Terminos", description: "El texto incluido aquí es un término de acuerdo al catálogo de términos y condiciones que se tenga por producto o servicio, sin embargo, el usuario podrá modificarlo.", default: 1)
Tax.create(name:"IVA", description: "Impuesto al Valor Agregado", amount: 0.16, value:0.16, default: 1)
TypeServiceOrder.create(name:"Mantenimiento", description: "Servicio de mantenimiento")
TypeServiceOrder.create(name:"Reparación", description: "Servicio de reparación")
TypeServiceOrder.create(name:"Otro", description: "Otros servicios")
DiagnosisType.create(name:"Reparación general", description: "Esto es una descripción")
DiagnosisType.create(name:"Mantenimiento general", description: "Esto es una descripción")
DiagnosisType.create(name:"Limpieza y mantenimiento", description: "Esto es una descripción")
DiagnosisType.create(name:"Reparación", description: "Esto es una descripción")
DiagnosisType.create(name:"Garantia de servicios", description: "Esto es una descripción")
DiagnosisType.create(name:"Garantia de piezas", description: "Esto es una descripción")
PaymentMethod.create(name:"Efectivo", description: "Esto es una descripción", payment_method_key:"01")
PaymentMethod.create(name:"Cheque nominativo", description: "Esto es una descripción", payment_method_key:"02")
PaymentMethod.create(name:"Transferencia electrónica de fondos", description: "Esto es una descripción", payment_method_key:"03")
PaymentMethod.create(name:"Tarjeta de crédito", description: "Esto es una descripción", payment_method_key:"04")
PaymentMethod.create(name:"Tarjeta de débito", description: "Esto es una descripción", payment_method_key:"28")
PaymentMethod.create(name:"Por definir", description: "Esto es una descripción", payment_method_key:"99")
PaymentWay.create(name:"Pago en una sola exhibición", description: "Esto es una descripción", payment_way_key: "PUE")
PaymentWay.create(name:"Pago en parcialidades o diferido", description: "Esto es una descripción", payment_way_key:"PPD")
UsersCustomer.create(user_id: 2, customer_id: 1)
EntryCode.create(name:"Devolución de venta", description: "Esto es una descripción")
EntryCode.create(name:"Entrada de fabrica", description: "Esto es una descripción")
EntryCode.create(name:"Cancelación de factura", description: "Esto es una descripción")
EntryCode.create(name:"Cancelación devolución de compra", description: "Esto es una descripción")
EntryCode.create(name:"Ajustes", description: "Esto es una descripción")
EntryCode.create(name:"Ajustes por traspaso", description: "Esto es una descripción")
ReceiptType.create(name:"Nota", description: "Esto es una descripción")
ReceiptType.create(name:"Factura", description: "Esto es una descripción")
UseOfCfdi.create(cfdi_key:"G01", name: "Adquisición de mercancias.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"G02", name: "Devoluciones, descuentos o bonificaciones.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"G03", name: "Gastos en general.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I01", name: "Construcciones.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I02", name: "Mobilario y equipo de oficina por inversiones.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I03", name: "Equipo de transporte.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I04", name: "Equipo de computo y accesorios.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I05", name: "Dados, troqueles, moldes, matrices y herramental.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I06", name: "Comunicaciones telefónicas.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I07", name: "Comunicaciones satelitales.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"I08", name: "Otra maquinaria y equipo.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D01", name: "Honorarios médicos, dentales y gastos hospitalarios.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D02", name: "Gastos médicos por incapacidad o discapacidad.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D03", name: "Gastos funerales.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D04", name: "Donativos.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D05", name: "Devoluciones, descuentos o bonificaciones.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"G02", name: "Intereses reales efectivamente pagados por créditos hipotecarios (casa habitación).", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D06", name: "Aportaciones voluntarias al SAR.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D07", name: "Primas por seguros de gastos médicos.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D08", name: "Gastos de transportación escolar obligatoria.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D09", name: "Depósitos en cuentas para el ahorro, primas que tengan como base planes de pensiones.", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"D10", name: "Pagos por servicios educativos (colegiaturas).", persona_fisica: 1, persona_moral:1)
UseOfCfdi.create(cfdi_key:"P01", name: "Por definir.", persona_fisica: 1, persona_moral:1)
Account.create(name:"Cuenta bancaria", description: "Cuenta bancaria")
Account.create(name:"Tarjeta de crédito", description: "Tarjeta de crédito")
Account.create(name:"Caja chica", description: "Caja Chica")
Account.create(name:"Otros", description: "Otros")
DocumentType.create(name:"Nota", description: "Nota")
DocumentType.create(name:"Factura", description: "Factura")